/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as ProtectedPartyImport } from './routes/_protected/party'
import { Route as ProtectedPackageImport } from './routes/_protected/package'
import { Route as ProtectedItemImport } from './routes/_protected/item'
import { Route as ProtectedCrockeryImport } from './routes/_protected/crockery'
import { Route as ProtectedCoastingImport } from './routes/_protected/coasting'
import { Route as authLoginImport } from './routes/(auth)/login'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedPartyRoute = ProtectedPartyImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedPackageRoute = ProtectedPackageImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedItemRoute = ProtectedItemImport.update({
  id: '/item',
  path: '/item',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedCrockeryRoute = ProtectedCrockeryImport.update({
  id: '/crockery',
  path: '/crockery',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedCoastingRoute = ProtectedCoastingImport.update({
  id: '/coasting',
  path: '/coasting',
  getParentRoute: () => ProtectedRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/_protected/coasting': {
      id: '/_protected/coasting'
      path: '/coasting'
      fullPath: '/coasting'
      preLoaderRoute: typeof ProtectedCoastingImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/crockery': {
      id: '/_protected/crockery'
      path: '/crockery'
      fullPath: '/crockery'
      preLoaderRoute: typeof ProtectedCrockeryImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/item': {
      id: '/_protected/item'
      path: '/item'
      fullPath: '/item'
      preLoaderRoute: typeof ProtectedItemImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/package': {
      id: '/_protected/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof ProtectedPackageImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/party': {
      id: '/_protected/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof ProtectedPartyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteChildren {
  ProtectedCoastingRoute: typeof ProtectedCoastingRoute
  ProtectedCrockeryRoute: typeof ProtectedCrockeryRoute
  ProtectedItemRoute: typeof ProtectedItemRoute
  ProtectedPackageRoute: typeof ProtectedPackageRoute
  ProtectedPartyRoute: typeof ProtectedPartyRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCoastingRoute: ProtectedCoastingRoute,
  ProtectedCrockeryRoute: ProtectedCrockeryRoute,
  ProtectedItemRoute: ProtectedItemRoute,
  ProtectedPackageRoute: ProtectedPackageRoute,
  ProtectedPartyRoute: ProtectedPartyRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedRouteWithChildren
  '/login': typeof authLoginRoute
  '/coasting': typeof ProtectedCoastingRoute
  '/crockery': typeof ProtectedCrockeryRoute
  '/item': typeof ProtectedItemRoute
  '/package': typeof ProtectedPackageRoute
  '/party': typeof ProtectedPartyRoute
  '/': typeof ProtectedIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/coasting': typeof ProtectedCoastingRoute
  '/crockery': typeof ProtectedCrockeryRoute
  '/item': typeof ProtectedItemRoute
  '/package': typeof ProtectedPackageRoute
  '/party': typeof ProtectedPartyRoute
  '/': typeof ProtectedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_protected/coasting': typeof ProtectedCoastingRoute
  '/_protected/crockery': typeof ProtectedCrockeryRoute
  '/_protected/item': typeof ProtectedItemRoute
  '/_protected/package': typeof ProtectedPackageRoute
  '/_protected/party': typeof ProtectedPartyRoute
  '/_protected/': typeof ProtectedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/coasting'
    | '/crockery'
    | '/item'
    | '/package'
    | '/party'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/coasting'
    | '/crockery'
    | '/item'
    | '/package'
    | '/party'
    | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/(auth)/login'
    | '/_protected/coasting'
    | '/_protected/crockery'
    | '/_protected/item'
    | '/_protected/package'
    | '/_protected/party'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  authLoginRoute: authLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/_protected",
        "/(auth)/login"
      ]
    },
    "/_protected": {
      "filePath": "_protected.jsx",
      "children": [
        "/_protected/coasting",
        "/_protected/crockery",
        "/_protected/item",
        "/_protected/package",
        "/_protected/party",
        "/_protected/"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.jsx"
    },
    "/_protected/coasting": {
      "filePath": "_protected/coasting.jsx",
      "parent": "/_protected"
    },
    "/_protected/crockery": {
      "filePath": "_protected/crockery.jsx",
      "parent": "/_protected"
    },
    "/_protected/item": {
      "filePath": "_protected/item.jsx",
      "parent": "/_protected"
    },
    "/_protected/package": {
      "filePath": "_protected/package.jsx",
      "parent": "/_protected"
    },
    "/_protected/party": {
      "filePath": "_protected/party.jsx",
      "parent": "/_protected"
    },
    "/_protected/": {
      "filePath": "_protected/index.jsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
